[package]
name = "bcrypte"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bcrypte"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
bcrypt = "0.15"
